site_name: Wiki
site_description: wiki
repo_url: https://github.com/DaiCae/wiki
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 DaiCae, All rights reserved.

theme:
  name: material
  favicon: blob/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.prune
    - header.autohide
    - toc.follow
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette#primary-color
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      accent: lime
      toggle:
        icon: material/brightness-7

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: yellow
      toggle:
        icon: material/brightness-4
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  # info warn error ...
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # highlight
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      # anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.snippets
  - def_list

extra:
  # homepage: http://baidu.com
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DaiCae

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
